DROP DATABASE IF EXISTS robinhood_db_test;
CREATE DATABASE robinhood_db_test;

\c robinhood_db_test;

DROP TABLE IF EXISTS analysts;
CREATE TABLE "analysts" (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data jsonb NOT NULL
);

DROP TABLE IF EXISTS stocks;
CREATE TABLE "stocks" (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data jsonb NOT NULL
);

DROP TABLE IF EXISTS analyst_ratings;
CREATE TABLE "analyst_ratings" (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "analysts_id" int REFERENCES analysts(id) ON DELETE CASCADE, 
  "stocks_id" int REFERENCES stocks(id) ON DELETE CASCADE,
  "rating" text,
  "rating_date" DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE INDEX "FK" ON  "analyst_ratings" ("analysts_id", "stocks_id");